/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly HONO_SERVER: string
  readonly ZERO_SERVER: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}